# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood'),
        ),
    ]
