# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0004_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Profile'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='neighborhood',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood'),
        ),
    ]
