# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0005_auto_20191029_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Profile'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood'),
        ),
    ]
