# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-25 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0008_auto_20191029_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neighborhood.Neighborhood'),
        ),
    ]
